version: '3.8'

services:

  # PostgreSQL
  postgre_sql:
    image: postgres:15.2
    restart: always
    container_name: postgre_sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # ----- #
      - postgres_data:/var/lib/postgresql/data
      # ----- #
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgres_data:


networks:
  my-network:
    driver: bridge
