version: '3.7'

services:

  postgresql_db:
    image: postgres:15.2
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgres_data:


networks:
  my-network:
    driver: bridge
